// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvzUblS4FIdT-4E3VTgkisuEXFcbAiL5o',
    appId: '1:213652988242:web:582a4821c7a36aadc69a8b',
    messagingSenderId: '213652988242',
    projectId: 'ecommerceapp-9ae04',
    authDomain: 'ecommerceapp-9ae04.firebaseapp.com',
    storageBucket: 'ecommerceapp-9ae04.appspot.com',
    measurementId: 'G-PH8ZR2M018',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB275DLUFGxqUze-DPTjcj9yLkSmG4pFiM',
    appId: '1:213652988242:android:f8c123c71e2dbec7c69a8b',
    messagingSenderId: '213652988242',
    projectId: 'ecommerceapp-9ae04',
    storageBucket: 'ecommerceapp-9ae04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtWdOq2Qw93PLOJlyxBsoqmGQh0ukRPPk',
    appId: '1:213652988242:ios:9132142a2016e442c69a8b',
    messagingSenderId: '213652988242',
    projectId: 'ecommerceapp-9ae04',
    storageBucket: 'ecommerceapp-9ae04.appspot.com',
    iosClientId: '213652988242-0rgr6upfbac084spnc33b3nogl4b66df.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
